name: 'Bit Verify'
description: 'Verify issues in bit components'
branding: 
  icon: 'check'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
