name: 'Bit Verify'
description: 'Verify issues in bit components'
branding: 
  icon: 'check'
  color: 'purple'
inputs:
  ws-dir:
    description: "Workspace json file directory path"
    required: false
  skip-build:
    description: "Skip running 'bit build'"
    required: false
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Run Bit Initialization Script
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        WS_DIR: ${{ inputs.ws-dir }}
