name: Test Bit Verify
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build action
        run: pnpm run build
      
      - name: Test build output
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "Build failed: dist/index.js not found"
            exit 1
          fi
          echo "Build successful!"

  verify:
    runs-on: ubuntu-latest
    needs: test
    env:
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_CONFIG_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Build action
        run: pnpm run build
      
      - name: Initialize Bit
        uses: bit-tasks/init@main
        with:
            ws-dir: 'test-data'
      
      - name: Bit Verify (using built action)
        uses: ./
        with:
          ws-dir: 'test-data'