name: Test Bit Verify
on:
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    env:
      BIT_CONFIG_ACCESS_TOKEN: ${{ secrets.BIT_CONFIG_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Initialize Bit
        uses: bit-tasks/init@main
        with:
            ws-dir: 'test-data'
      - name: Bit Verify
        uses: bit-tasks/verify@use-ci-scripts